AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31


Globals:
  Function:
    Timeout: 3


Resources:

  ServerlessFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: latest
      DockerContext: ./src
      Dockerfile: Dockerfile
    Properties:
      FunctionName: !Ref AWS::StackName
      PackageType: Image
      ImageUri: !Ref AWS::StackName
      Policies:
      - AWSLambdaBasicExecutionRole
